# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Jorge/Documents/LabHLS_RS2016_4/LabHLS_RS2016_4.cache/wt [current_project]
set_property parent.project_path C:/Users/Jorge/Documents/LabHLS_RS2016_4/LabHLS_RS2016_4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/Jorge/Documents/reed_solomon_erasure/ProjRSErasure/SolutionX/impl/ip [current_project]
set_property ip_output_repo c:/Users/Jorge/Documents/LabHLS_RS2016_4/LabHLS_RS2016_4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Jorge/Documents/LabHLS_RS2016_4/LabHLS_RS2016_4.srcs/sources_1/new/StateMachine.v
  C:/Users/Jorge/Documents/LabHLS_RS2016_4/LabHLS_RS2016_4.srcs/sources_1/imports/lab3/meta_harden.v
  C:/Users/Jorge/Documents/LabHLS_RS2016_4/LabHLS_RS2016_4.srcs/sources_1/imports/lab3/uart_baud_gen.v
  C:/Users/Jorge/Documents/LabHLS_RS2016_4/LabHLS_RS2016_4.srcs/sources_1/imports/lab3/uart_rx.v
  C:/Users/Jorge/Documents/LabHLS_RS2016_4/LabHLS_RS2016_4.srcs/sources_1/imports/lab3/uart_rx_ctl.v
  C:/Users/Jorge/Documents/LabHLS_RS2016_4/LabHLS_RS2016_4.srcs/sources_1/new/topmodule.v
}
add_files C:/Users/Jorge/Documents/LabHLS_RS2016_4/LabHLS_RS2016_4.srcs/sources_1/bd/design_2/design_2.bd
set_property used_in_implementation false [get_files -all c:/Users/Jorge/Documents/LabHLS_RS2016_4/LabHLS_RS2016_4.srcs/sources_1/bd/design_2/ip/design_2_rs_erasure_0_0/constraints/rs_erasure_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Jorge/Documents/LabHLS_RS2016_4/LabHLS_RS2016_4.srcs/sources_1/bd/design_2/design_2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Jorge/Documents/LabHLS_RS2016_4/LabHLS_RS2016_4.srcs/constrs_1/imports/lab3/uart_led_pins_basys3.xdc
set_property used_in_implementation false [get_files C:/Users/Jorge/Documents/LabHLS_RS2016_4/LabHLS_RS2016_4.srcs/constrs_1/imports/lab3/uart_led_pins_basys3.xdc]

read_xdc C:/Users/Jorge/Documents/LabHLS_RS2016_4/LabHLS_RS2016_4.srcs/constrs_1/imports/lab3/uart_led_timing.xdc
set_property used_in_implementation false [get_files C:/Users/Jorge/Documents/LabHLS_RS2016_4/LabHLS_RS2016_4.srcs/constrs_1/imports/lab3/uart_led_timing.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top topmodule -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef topmodule.dcp
create_report "synth_4_synth_report_utilization_0" "report_utilization -file topmodule_utilization_synth.rpt -pb topmodule_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
