# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab3/uart_led_pins_basys3.xdc

# XDC: imports/lab3/uart_led_timing.xdc

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2}]

# IP: bd/design_2/ip/design_2_rs_erasure_0_0/design_2_rs_erasure_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_rs_erasure_0_0 || ORIG_REF_NAME==design_2_rs_erasure_0_0}]

# XDC: bd/design_2/ip/design_2_rs_erasure_0_0/constraints/rs_erasure_ooc.xdc

# XDC: bd/design_2/design_2_ooc.xdc
